### PR TITLE
Boresch Restraints for Absolute Binding Free Energy Calculations

### PR DESCRIPTION
**Pull request by fjclark**
Hello,

I've implemented [Boresch restraints](https://pubs.acs.org/doi/full/10.1021/jp0217839) for ABFE calculations, trying to follow the implementation of the distance restraints as closely as possible. I've also implemented the analytical correction (Equation 32 of the paper) and semi-analytical correction for releasing these restraints to the standard state. The code for the latter is very closely based on [restraints.py](https://github.com/choderalab/yank/blob/master/Yank/restraints.py) in Yank - I have acknowledged this, and my understanding is that this is fine due to the compatibility of the MIT and GNU GPL licenses.

This allows ABFE calculations with Boresch restraints to be run in three stages:

- The Boresch restraints are turned on by linearly scaling the force constants with lambda. A dummy pert file must be supplied which maps parameters onto themselves. The following must be specified in the config file:
```
use boresch restraints = True
boresch restraints dictionary = {"anchor_points":{"r1":4946, "r2":4944, "r3":4949, "l1":11, "l2":2, "l3":3},"equilibrium_values":{"r0":5.92, "thetaA0":1.85, "thetaB0":1.59,"phiA0":-0.30, "phiB0":-1.55, "phiC0":2.90},"force_constants":{"kr":25.49, "kthetaA":66.74, "kthetaB":38.39, "kphiA":215.36, "kphiB":49.23, "kphiC":49.79}}
turn on receptor-ligand restraints mode = True

```
- Vanishing and discharging stages are completed as with multiple distance restraints.

I originally defined the force constants as F = k\*x, as in the original paper, but I have changed this to F = 2\*k\*x to be as consistent as possible with the multiple distance restraints. The corrections can be calculated by feeding any config file containing a Boresch restraints dictionary to the correction apps, for example:

```
boresch_analytical_correction -C ../input/sim.cfg
```

I have begun work on tests, but I am unsure of the best approach. I was planning to copy most of the functionality over from OpenMMMD.py to set up a system with and without restraints, and test for the correct difference in energies. Do you have any recommendations?

Thanks very much,
Finlay

### CODE REVIEW

**Comment by chryswoods** [comment]
Thanks @fjclark. It looks good. We will try to find a way to get the GitHub Actions to run so that we can test it, but I think it should be fine.

Yes, you are right that you can include MIT (or any properly open source license, like Apache, BSD etc) code in a GPL package. The licenses are compatible. We just have to retain copyright notices and make sure that, if code is inspired by another code, that attribution and the original license and copyright is recorded somewhere. As part of the `feat_web` work, I am creating a new website that provides extra attribution for such code, e.g. [see here](https://github.com/michellab/Sire/blob/feat_web/doc/source/acknowledgements.rst).

Speaking of `feat_web`, your pull request and work should not be impacted by it. I'll do the work to pull your change into `feat_web` and also sort out the new way that we will be handling the tests :-)

**Comment by lohedges** [comment]
Apologies for the delay with this @fjclark. I'll take a look on a local copy to see if I can resolve the conflicts and apply any 2023 related updates. I'm a bit confused why this would revert certain changes, i.e. those in the `CHANGELOG`, but I guess this is to do with the point at which your fork was made.

**Comment by lohedges** [comment]
Hi @fjclark. I've done the work to update your scripts for the 2023 API and have also dealt with the various conflicts. This has been pushed to the [feature-boresch](https://github.com/michellab/Sire/tree/feature-boresch) branch. Could you take a look at this and let me know when you are happy?

**Comment by fjclark** [comment]
Hi @lohedges, thanks very much for this - looks good. A couple of small comments:

- Would be be good to remove these two lines, given that PBC checks now work? https://github.com/michellab/Sire/blob/6ee686926a8c7d3176b2a788bc6223415c8bb0cc/corelib/src/libs/SireMove/openmmfrenergyst.cpp#L1234
-  Could we keep lamrest in this expression, as in my PR, to allow distance restraints to be scaled with lamrest in the same way as Boresch restraints? https://github.com/michellab/Sire/blob/6ee686926a8c7d3176b2a788bc6223415c8bb0cc/corelib/src/libs/SireMove/openmmfrenergyst.cpp#L1238

Otherwise I'm happy.

Cheers.

**Comment by lohedges** [comment]
No problem, I'll add these tomorrow. I must have missed them when updating. (I had to manually edit certain files because of the conflicts.)

**Comment by fjclark** [comment]
Perfect, thanks.

**Comment by lohedges** [comment]
Closed as incorporated via b9ef695.

**Pull request closed without merging**
