### PR TITLE
Devel

### PR DESCRIPTION
**Pull request by Steboss**
OpenMMMD.py specific restraint and equilibration iterations

### CODE REVIEW

**Comment by jmichel80** [comment]
* When you submit a merge request, be more verbose with your comments so people can understand what 'specific restraint' is and what the equilibration iterations problem was. 

* You also need to commit the updated openmmfrenergyst.cpp file to fix the incorrect order of streaming shareddatastream objects. Make sure that your committed version doesn't have debugging flags turned on. 

* Typo line 134 --> harmonic restaints --> restraints

* Why does your 'specific restraints' subroutine also restraints atoms based on their mass ? It isn't logical. Can you propose a more meaningful name for this subroutine? positional_restraints_by_name? What if there is more than one atom with the same name ? Should we select by index instead ? 

* ....Overall, do not include specific restraints in the devel branch as it is currently not sufficiently tested and well thought to be made available to other developers/users.

**Comment by ppxasjsm** [comment]
I will try and include an auto build using travis at least for the c++ part of sire, so that it becomes obvious when pushed code might be broken.

**Comment by ppxasjsm** [comment]
For ongoing development of a feature just create a feature branch:
git branch feature_restraint
git checkout feature_restraint
do your changes
git add changed_files*
git commit -m '[restraint] meaningful message'
git push origin feature_restraint
In theory you can then make a pull request to the main repository with the feature (to a feature branch), or wait until it has matured and add it to the level when all issues are tested. Not sure how to handle this.

**Comment by jmichel80** [comment]
Stefano, please make a push request to devel with just the bugfixes to
handle correctly equilibration or to assign the variable k_restraints.

Create a separate feature_branch to test your new restraints code. Think
about how to make the code able to handle a wide range of selection of
atoms (by name, index etc...) and write test scripts to be added to
'wrapper/tests/OpenMM' . When you are happy that the code works as expected
we will consider again merging with devel.


--------------------------------------------------------------
Dr. Julien Michel,
Royal Society University Research Fellow
Room 263, School of Chemistry
Joseph Black Building, University of Edinburgh
David Brewster Road

Edinburgh

EH9 3FJ
United Kingdom
phone:   +44 (0)131 650 4797
http://www.julienmichel.net/
-------------------------------------------------------------

On Tue, Jun 30, 2015 at 4:20 PM, ppxasjsm <notifications@github.com> wrote:

> For ongoing development of a feature just create a feature branch:
> git branch feature_restraint
> git checkout feature_restraint
> do your changes
> git add changed_files*
> git commit -m '[restraint] meaningful message'
> git push origin feature_restraint
> In theory you can then make a pull request to the main repository with the
> feature (to a feature branch), or wait until it has matured and add it to
> the level when all issues are tested. Not sure how to handle this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/michellab/Sire/pull/14#issuecomment-117225906>.
>

The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by Steboss** [comment]
I have fixed the incorrect order of streaming shareddatastream objects in openmmfrenergyst.cpp
Fixed also OpenMMMD.py code in setupMovesFreeenergy in order to handle correctly equilibration options

**Comment by jmichel80** [comment]
Antonia, can you check with Stefano whether the pull request should be merged if the Travis build failed ? I'm assuming it failed because travis is not setup correctly at the moment

**Pull request merged**
