### PR TITLE
Fixed ViewsOfMol bugs in OpenMMMD.py, DCDFile.py and LJCutoff.py

### PR DESCRIPTION
**Pull request by Steboss**
Fixed the issue #159 : 
-- modified in OpenMMMD.py  "system.molecule(molnum).molecules()" with "system.molecule(molnum)[0]"  to take 1 element from the list of ViewsOfMols. 

-- modified DCDFile.py as above to save correctly the snapshot form the system 

-- modified LJCutoff.py. In this case we need to take correctly a "Molecule" object and not a "PartialMolecule", thus the right element from the list of ViewsOfMols is always the last one, thus [-1] in the script.

### CODE REVIEW

**Comment by jmichel80** [comment]
-- modified LJCutoff.py. In this case we need to take correctly a "Molecule" object and not a "PartialMolecule", thus the right element from the list of ViewsOfMols is always the last one, thus [-1] in the script.

@chryswoods can you confirm this is the intended behaviour? I find it unintuitive.

**Comment by jmichel80** [comment]
@Steboss can you investigate why the CI build failed

**Comment by chryswoods** [comment]
You shouldn't assume that the last MoleculeView in LJCutoff.py is a Molecule and not a PartialMolecule. If you want a Molecule, then use .molecule() on the first view, e.g.

```python
mol = system.molecule(molnum)[0].molecule()
```

I agree that the API is not as nice as I'd like when there are multiple views of a molecule within a System. The change is an effort to simplify the API in the simple case (there is only a single view), but at the expense of complicating the API for the general case (there are multiple views). The rationale is that the simple case is the one encountered most often when learning Sire and in tutorials, and having to learn about ViewsOfMol in the first tutorial is quite a barrier.

As a note, we should clean up the API a little by adding indexing operators to system, so that you could type

```python
mol = system[molnum][0].molecule()
```

or, if we wanted, we could say that the indexing operator automatically squashes all of the different views into a single view, so we could type

```python
mol = system[molnum].molecule()
```
or
```python
view = system[molnum]
```

What do you think?

**Comment by Steboss** [comment]
Hi Chris,

I didn't know exactly how to handle the MoleculeViews, thus I just opted for the latest element. I will fix LJcutoff and OpenMMMD.py accordingly, in order to select the right molecule. 
I would really like a more simple way to deals with molecule in the API and something like:
```
mol = system[molnum].molecule()
```
or 
``` 
view = system[molnum]
```
could be really great

**Pull request merged**
