### PR TITLE
Multi lambda feature

### PR DESCRIPTION
**Pull request by ppxasjsm**
Made changes that now and outputdata_file can be written that allows a free energy analysis using mbar/bar or TI. The default name of the outputdata_file is "simfile.dat", but can be changed in the configuration file. 
All data is written out either in kcal/mol or dimensionless. 
All small tests have passed so far, with larger systems currently running.

### CODE REVIEW

**Comment by jmichel80** [comment]
Hi Antonia,

A minor quibble. forward_metropolis and backward_metropolis are treated
differently to finite_diff_gradients, pot_energies and
reduced_perturbed_energies, yet all are ensemble averages.

This happens because in OpenMMFrEnergyST::calculateGradient the gradients
are computed and returned, but forward_metropolis and backward_metropolis
values are immediately appended to the arrays.

For clarity I suggest to have calculateGradient return a the three numbers,
and to append all ensemble averages in the same section of ::integrate()

Looking forward to use the new code !

Best wishes,

Julien

On Tuesday, August 18, 2015, ppxasjsm <notifications@github.com> wrote:

> Made changes that now and outputdata_file can be written that allows a
> free energy analysis using mbar/bar or TI. The default name of the
> outputdata_file is "simfile.dat", but can be changed in the configuration
> file.
> All data is written out either in kcal/mol or dimensionless.
> All small tests have passed so far, with larger systems currently running.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/michellab/Sire/pull/51
> Commit Summary
>
>    - [ci skip][OpenMMFrEnST] moved pertrubed lambda calculation to
>    functions updateOpenMMContextLambda and getPotentialEnergyAtLambda
>    - [ci skip] [wrapper] updated the wrapper to be able to pass lambda
>    array to OpenMMFrEnST
>    - [ci skip] lambda updated in anneal lamabda replaced with function
>    updateOpenMMContextLambda()
>    - [ci skip] removed old ways of calculating delta A only doing finite
>    difference gradients now
>    - [ci skip] biased energies computation added
>    - [ci skip] renaming some of the variables and updating wrapper, added
>    old way of calculating free energy differences again
>    - [ci skip] wrapper updated to calculate forward and backward
>    perturbed energies for old style gradient calculation
>    - [ci skip] removing arrays from saving stream, since they are
>    nolonger needed for on the fly averaging
>    - merging in features from devel before making changes to OpenMMMD.py
>    - [OpenMMD] updated to allow for new style output file
>    - fixing bug of all container Qvectors not being emptied after one
>    cycle
>    - Bugfix in calculation of gradients via DU/DL if lambda near 1.0
>    - [ci skip] minor change
>    - [ci skip] minor change
>    - [ci skip][OpenMMMD] output file formatting improved
>    - [ci skip] Energy output updated to actual potential energy in free
>    energy calculations
>    - [ci skip] removing some old comments that are nolonger needed
>
> File Changes
>
>    - *M* corelib/src/libs/SireMove/openmmfrenergyst.cpp
>    <https://github.com/michellab/Sire/pull/51/files#diff-0> (468)
>    - *M* corelib/src/libs/SireMove/openmmfrenergyst.h
>    <https://github.com/michellab/Sire/pull/51/files#diff-1> (31)
>    - *M* wrapper/Move/OpenMMFrEnergyST.pypp.cpp
>    <https://github.com/michellab/Sire/pull/51/files#diff-2> (42)
>    - *M* wrapper/Tools/OpenMMMD.py
>    <https://github.com/michellab/Sire/pull/51/files#diff-3> (52)
>
> Patch Links:
>
>    - https://github.com/michellab/Sire/pull/51.patch
>    - https://github.com/michellab/Sire/pull/51.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/michellab/Sire/pull/51>.
>


-- 
--------------------------------------------------------------
Dr. Julien Michel,
Royal Society University Research Fellow
Room 263, School of Chemistry
Joseph Black Building, University of Edinburgh
David Brewster Road

Edinburgh

EH9 3FJ
United Kingdom
phone:   +44 (0)131 650 4797
http://www.julienmichel.net/
-------------------------------------------------------------

The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by ppxasjsm** [comment]
Mhh, I agree this isn't ideal. c++ only supports returning multiple variables from c++11 standard onwards which I am pretty sure we are not using. The other options all seem a bit problematic. 
- Class/struc gradient with public members: gradient, foward-metropolis and backward metropolis
- array of length 3 containing gradient, forward and backward metropolis
- append the finite_difference_gradient in the function (I lean towards this option)
I am not sure what best programming practice is in C++ here.

**Comment by jmichel80** [comment]
I would return a tuple<double, tuple<double,double> >

Qt may also have an appropriate container. Check Sire for similar cases or
the Qt docs.

- - -
Julien
Sent from my phone.
On 19 Aug 2015 11:03, "ppxasjsm" <notifications@github.com> wrote:

> Mhh, I agree this isn't ideal. c++ only supports returning multiple
> variables from c++11 standard onwards which I am pretty sure we are not
> using. The other options all seem a bit problematic.
>
>    - Class/struc gradient with public members: gradient,
>    foward-metropolis and backward metropolis
>    - array of length 3 containing gradient, forward and backward
>    metropolis
>    - append the finite_difference_gradient in the function (I lean
>    towards this option) I am not sure what best programming practice is in C++
>    here.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/michellab/Sire/pull/51#issuecomment-132523470>.
>

The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by ppxasjsm** [comment]
Ah ok, I have never used these. I'll have a look and implement this.

**Comment by ppxasjsm** [comment]
Took a moment for me to understand what is going on. Using tuples now instead of randomly appending. 
NB: after a bit of googling, it seems that the boost::tuples::tuple has now been included into the standard template library as of c++11, though I guess we are sticking with the boost implementation.

**Pull request merged**
