### PR TITLE
Feature hmr

### PR DESCRIPTION
**Pull request by jmichel80**
New PR after removing trailing whitespaces and other minor style changes

### CODE REVIEW

**Comment by jmichel80** [comment]
Should I manually delete feature_HMR ?

--------------------------------------------------------------
Dr. Julien Michel,
Royal Society University Research Fellow
Room 263, School of Chemistry
Joseph Black Building, University of Edinburgh
David Brewster Road

Edinburgh

EH9 3FJ
United Kingdom
phone:   +44 (0)131 650 4797
http://www.julienmichel.net/
-------------------------------------------------------------

On Wed, Aug 12, 2015 at 9:48 AM, ppxasjsm <notifications@github.com> wrote:

> Merged #49 <https://github.com/michellab/Sire/pull/49>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/michellab/Sire/pull/49#event-380073409>.
>

The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by ppxasjsm** [comment]
So here we can delete the branch, by clicking on the delete button. (Remote branch delete)
For your local copy 
git branch -d feature_HMR (local delete)
git push origin :feature_HMR (push the delete if you haven't done this yet with the button)
git fetch -p will update the branch list

**Comment by jmichel80** [comment]
I get his error message

julien@ubuntu:~/software/devel/git/sire/wrapper$ git status
# On branch feature_HMR
nothing to commit (working directory clean)
julien@ubuntu:~/software/devel/git/sire/wrapper$ git pull origin feature_HMR
From https://github.com/michellab/sire
 * branch            feature_HMR -> FETCH_HEAD
Already up-to-date.
julien@ubuntu:~/software/devel/git/sire/wrapper$ git branch -d feature_HMR
error: Cannot delete the branch 'feature_HMR' which you are currently on.
julien@ubuntu:~/software/devel/git/sire/wrapper$ git checkout devel
Switched to branch 'devel'
julien@ubuntu:~/software/devel/git/sire/wrapper$ git branch -d feature_HMR
error: The branch 'feature_HMR' is not fully merged.
If you are sure you want to delete it, run 'git branch -D feature_HMR'.
julien@ubuntu:~/software/devel/git/sire/wrapper$

Should I proceed with -D or is this telling us something hasn't worked with
the merging?



--------------------------------------------------------------
Dr. Julien Michel,
Royal Society University Research Fellow
Room 263, School of Chemistry
Joseph Black Building, University of Edinburgh
David Brewster Road

Edinburgh

EH9 3FJ
United Kingdom
phone:   +44 (0)131 650 4797
http://www.julienmichel.net/
-------------------------------------------------------------

On Wed, Aug 12, 2015 at 11:35 AM, ppxasjsm <notifications@github.com> wrote:

> So here we can delete the branch, by clicking on the delete button.
> (Remote branch delete)
> For your local copy
> git branch -d feature_HMR (local delete)
> git push origin :feature_HMR (push the delete if you haven't done this yet
> with the button)
> git fetch -p will update the branch list
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/michellab/Sire/pull/49#issuecomment-130252126>.
>

The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by ppxasjsm** [comment]
Dunno seems fine to me. Not sure why you get that error.

**Comment by ppxasjsm** [comment]
The merge has worked all the code changes are in devel.

**Pull request merged**
