### PR TITLE
Qube combining rules

### PR DESCRIPTION
**Pull request by SofiaBariami**
Implementation of geometric combining rules. The combining rules unit test in docker is successful for different values of lambda. 
eg: 
```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TESTING ARITHMETIC COMBINING RULES
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
* The energy from Sire is: 17.6162 kcal mol-1
* The energy from SOMD is: 17.6162 kcal mol-1
 For the arithmetic combining rules the single point energy difference between sire and somd at lambda 0.6 is 2.418878671761604e-05 
Energy function, does this ever get called?
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TESTING GEOMETRIC COMBINING RULES
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
* The energy from Sire is: 17.6162 kcal mol-1
* The energy from SOMD is: 17.6162 kcal mol-1
 For the geometric combining rules the single point energy difference between sire and somd at lambda 0.6 is 2.418878671761604e-05 

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The difference of the single point energies for a toluene- methane perturbation is 0.0 kcal/mol when using geometric and arithmetic combining rules
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### CODE REVIEW

**Comment by jmichel80** [comment]
Excellent. Can you run now a free energy calculation in vacuum to compute a free energy change using geometric or arithmetic combining rules. This will help test whether the full free energy code is working correctly.

**Comment by SofiaBariami** [comment]
Hello, hope you enjoyed Easter :) 
I was wondering if there have been any changes in Sire that could have affected the openmmfrenergy integrator. When I clone and install the qube-combiningRules branch, the compile fails with the following error: 
```
Executing transaction: failed
ERROR conda.core.link:_execute(507): An error occurred while installing package 'conda-forge::attrs-19.3.0-py_0'.
FileNotFoundError(2, "No such file or directory: '/home/sofia/sire-qube.app/bin/python3.8'")
Attempting to roll back.

Rolling back transaction: done

FileNotFoundError(2, "No such file or directory: '/home/sofia/sire-qube.app/bin/python3.8'")

Something went wrong installing dependencies!
```
The installation is successful when I install sire from the devel branch and then change the modified files of qube-combiningRules (opnemmmfrenergyst.* , OpenMMMD.py and OpenMMFrEnergyST.pypp.cpp). However, now now [this](https://github.com/michellab/SireUnitTests/blob/CombRules/unittests/SireMove/test_CombRules.py) Sire Unit Test gives different energies for the geometric combining rules, with the SOMD energy being the same as the Sire one: 
```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TESTING ARITHMETIC COMBINING RULES
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
* The energy from Sire is: 2.68694 kcal mol-1
* The energy from SOMD is: 2.68694 kcal mol-1
 For the arithmetic combining rules the single point energy difference between sire and somd at lambda 0.0 is -6.1208027108961005e-06 

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TESTING GEOMETRIC COMBINING RULES
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
* The energy from Sire is: 2.61428 kcal mol-1
* The energy from SOMD is: 2.68694 kcal mol-1
 For the geometric combining rules the single point energy difference between sire and somd at lambda 0.0 is -0.07266638703239892 

```
As you can see in the beginning of his thread, it used to work fine. 
Any thoughts on that? Thank you very much.

**Comment by jmichel80** [comment]
Hi Sofia

Don’t know why you get this conda error.
For your install over devel your SOMD energy is the same between arithmetic and geometric combing rules so the code is still executed with arithmetic even though you think you set geometric. Check if you set combining rules correctly within openmmfrenergyst.cpp

**Comment by lohedges** [comment]
Hi @SofiaBariami.

For the first part: Looking at the output it looks like you somehow have ended up with a Python 3.8 Conda environment. While Sire and BioSimSpace work fine with Python 3.8, the version of MiniConda that is used to build Sire currently comes with Python 3.7. Perhaps you updated something in your local `qube-combiningRules` branch that pulls in a newer Python as a dependency. (When building, make sure you delete the existing `sire.app` directory, the `build/corelib` and `build/wrapper `directories, and possibly the `build/miniconda.sh` file if it is out of date.)

For the second part: Without comparing what's different between the two branches it's hard to know. The only things that I have recently changed in Sire are improvements to the AmberPrm and GroTop parsers to avoid N^2 loops when collecting records for the intrascale matrix. You could always roll your `devel` repository back to an earlier date by checkout out a specific commit with something like:

```
git commit 45f875
```

(You can pass any amount of a git commit hash as long as it's enough to uniquely identify a commit.)

 Paolo made some changes to make sure that potential terms, e.g. dihedrals, are always sorted so that topology files are reproducible. As such, it could be an accumulation issue when computing the potential, i.e. the terms are added in a different order to before so you get a slightly different answer.

**Pull request closed without merging**
