### PR TITLE
Get Sire to work well on Windows

### PR DESCRIPTION
**Pull request by ptosco**
Description of this PR:

- implements `SireBase::Process` on Windows such that BSS works
- improves the build system on Windows
- fixes poor performance of AVX intrinsics on Windows when compiling with MSVC due to the functions using them not being inlined. The solution is to replace `inline` keywords with `SIRE_ALWAYS_INLINE` macros which resolve to `inline` on gcc/clang, and to `__forceinline` on MSVC. Before this, `MultiFloat` calls were 5x times (!!) slower on MSVC than on MinGW gcc and `MultiDouble` 2x times (!) slower, as assessed by running `sire_multitest`.
- fixes poor performance of parameter parsers on Windows due to `boost::stacktrace` being very slow on MSVC when caching is not enabled: defining `BOOST_STACKTRACE_USE_WINDBG_CACHED` fixes the problem and restores same performance os on MinGW gcc.

I downgraded boost to 1.69 in the conda build as the boost 1.70 Windows conda build seems broken (CMake cannot find some configuration files). I didn't want to spend a lot of time trying to fix it, as 1.69 works well. Please let me know if this is a problem.

### CODE REVIEW

**Comment by lohedges** [comment]
Hi @ptosco, thanks a lot for this, it looks great. I'll merge into a test branch locally to check that it builds for me.

With regards to `boost=1.70`: Although Sire doesn't explicitly require this, it's needed by the BioSImSpace Conda package. This is because we need to use the latest version of RDKit from `conda-forge` due to bug-fixes. Unfortunately the package is pinned to the latest version of Boost, i.e. this is from the `meta.yaml` of the package:

```
    run:
        - boost >=1.70.0,<1.70.1.0a0
```

Although we could use the RDKit Conda package from the `rdkit` channel instead, since this uses an older version of Boost, we've been trying to reduce our channel dependency with the ultimate goal of moving to `conda-forge` once OpenMM has moved there too.

Would it be possible to to use `sys.platform` to selectively install version 1.69 if the build is run on WIndows?

**Comment by ptosco** [comment]
@lohedges I found a solution to the Boost 1.70.0 issue on Windows.

**Comment by lohedges** [comment]
Everything builds fine for me and all Sire and BioSimSpace tests pass. The only thing that I've come across is that the informative output when killing a process interactively has been lost. For example:

Existing BioSImSpace behaviour
```python
process.kill()
Killing job  /home/lester/Downloads/amber18/bin/sander -O -i amber.cfg -p amber.prm7 -c amber.rst7 -o stdout -r amber.crd -inf amber.nrg
```

Following changes to Sire.Base.Process
```
process.kill()
waitpid exited with status -1! No child processes
```

The process has still been killed, but the message hasn't been printed:

Existing code:
```cpp
    //kill the job
    if (d->is_running)
    {
        testWait();

        if (d->is_running)
        {
            qDebug() << "Killing job " << d->command.toUtf8().constData()
                    << d->arguments.join(" ").toUtf8().constData();
            killpg(d->pid, SIGKILL);
        }
        else
            return;
    }
```

New code:
```cpp
    //kill the job
    if (d->is_running)
    {
        testWait();

        if (d->is_running)
            d->kill_process_group();
        else
            return;
    }
```

For some reason the `if (status == -1)` condition was triggered:

New code:
```cpp
/** Test the process to see if it's still running. If it has just finished, clean up
    and set appropriate flags. WARNING: You must hold datamutex while calling this
    function. */
void Process::testWait()
{
    if (not d->is_running)
        return;

    #ifndef Q_OS_WIN
    int child_exit_status;
    int status;

    status = waitpid(d->pid, &child_exit_status, WNOHANG);

    if (status == 0)
        return;

    if (status == -1)
    {
        qDebug() << "waitpid exited with status -1!" << strerror(errno);

        d->is_running = false;
        d->pid = 0;
        return;
    }
    else if (status != d->pid)
    {
        qDebug() << "waitpid exited with the wrong PID (" << status
                    << "vs." << d->pid << ")" << strerror(errno);

        d->is_running = false;
        d->pid = 0;
        return;
    }
    #else
    DWORD child_exit_status;
    BOOL status = GetExitCodeProcess(d->proc_info.hProcess, &child_exit_status);
    if (!status)
    {
        qDebug() << "GetExitCodeProcess() exited with error code" << GetLastError();

        d->is_running = false;
        return;
    }
    #endif

    if ( processRunning(child_exit_status) )
    {
        return;
    }
    else
    {
        //the job has finished - process the finished job
        this->cleanUpJob(status, child_exit_status);
        return;
    }
}
```

But not in the existing code (equivalent section)

```cpp
/** Wait until the process has finished */
void Process::wait()
{
    if (d.get() == 0)
        return;

    QMutexLocker lkr( &(d->datamutex) );

    if (not d->is_running)
        return;

    int child_exit_status;
    int status = waitpid(d->pid, &child_exit_status, 0);

    if (status == -1)
    {
        qDebug() << "waitpid exited with status -1!" << strerror(errno);
        return;
    }
    else if (status != d->pid)
    {
        qDebug() << "waitpid exited with the wrong PID (" << status
                 << "vs." << d->pid << ")" << strerror(errno);
        return;
    }

    if ( processRunning(child_exit_status) )
    {
        qDebug() << "child process has not finished!";
    }
    else
    {
        this->cleanUpJob(status, child_exit_status);
    }
}
```

**Comment by ptosco** [comment]
Thanks, I'll look into this.

**Comment by lohedges** [comment]
I'm not so bothered about the first bit, i.e. missing the `Killing job...` message since I can always choose to print something similar from within `BioSimSpace.Process`, but it would be good to avoid the `waitpid` error message if it's not actually necessary.

**Comment by ptosco** [comment]
@lohedges Fixed. Thanks a lot for catching this regression I had inadvertently introduced!

**Comment by lohedges** [comment]
All okay at this end, happy to merge.

**Pull request merged**
