### PR TITLE
Bug fix

### PR DESCRIPTION
**Pull request by ppxasjsm**
added the following features:
--discard for mbar subcommand to just discard initial lines from simulation files

Arguments that are not recognised with mbar subcommand are now thrown and error given. 

Temperature is now read from simulation file, if not given over command line and checked for consistency if provided by command line.

### CODE REVIEW

**Comment by jmichel80** [comment]
l175                         help="Number of saved simualtion snapshots that should be discarded at the beginning of a trajectory") 
--> typo 

l462-465
+        if args.percent:
 +            percentage = args.percent
 +        else:
 +            percentage = 95.0

--> is this compatible with the default behaviour of analyse_freenrg ? 

l534
+                            T = float(temp)+273
--> 
celsius to kelvin is +273.15
 
read units from simfile ? Sire has support for temperatures. 

same for l560-576

l627-631
 if subsample_obj.gradients_kn.shape[1]<50:
            ti_warn_msg = ' #WARNING SUBSAMLING GRADIENTS RESULTED IN LESS THAN 50 SAMPLES, CONSIDER RERUN WITHOUT SUBSAMPLE OPTION'

        if subsample_obj.u_kln.shape[2]<50:
            mbar_warn_msg = ' #WARNING SUBSAMLING ENERGIES RESULTED IN LESS THAN 50 SAMPLES, CONSIDER RERUN WITHOUT SUBSAMPLE OPTION'

--> Typos 

line 642-643
                    'Off diagonal elements of the overlap matrix are smaller than 0.03! Your free energy estiamte is '
                    'not reliable!')

--> Typo

**Comment by ppxasjsm** [comment]
In terms of temperature. There is a rounding issue somewhere then. Because if we pass temperature in K then 25 C is spat out in the simulation file, however 25 C should be 298.15K. I am tempted to remove the --temperature option from the command line and just read the temperature from the simulation file. That seems to be more consistent.

**Comment by ppxasjsm** [comment]
The 95% is just the default for the mbar subcommand. The 60% default of the analyse free energy does not give reliable mbar/ti compatible estimates.

**Comment by jmichel80** [comment]
Ok to remove temperature,  I don't see why the user would input a temperature different from the simulation temperature, or if there is a need for it this is non standard usage and can be done by hacking simfile

The default T for somd is at l 54 in OpenMMMD.py
temperature = Parameter("temperature", 25 * celsius, """Simulation temperature""")

Check that this is correctly overwritten by a config file that lists temperature as an option.

**Comment by ppxasjsm** [comment]
Ok will remove temperature as an option and make sure conversion between K and C is done correctly. I guess we rarely touch the default temperature then, at least none of my config files have a non default temperature option. I somehow remembered that the default was in Kelvin and not °C, but clearly I am wrong there. Does Sire support F?

**Comment by jmichel80** [comment]
Yes, check all the units supported here

https://github.com/michellab/Sire/tree/devel/corelib/src/libs/SireUnits

The idea is that you shouldn't have to remember in what units a given float is in the code. 
The units code is not perfect and a bit cumbersome at times, so I don't always bother using it in rough scripts, but it's a good idea to rely on for critical code to be used by others.

**Comment by jmichel80** [comment]
I have no other comments. Please merge when all above issues have been fixed.

**Comment by jmichel80** [comment]
Ok to merge the bugfix ? Will run tests on devel with --discard

**Pull request merged**
