### PR TITLE
Feature pmefep

### PR DESCRIPTION
**Pull request by jmichel80**
This PR brings significant code updates from @halx on feature_pmefet to allow further development and testing of experimental PME support for SOMD with the 2023 Sire build system implemented by @lohedges and @chryswoods 
PR done against feature_pme_fep_2023 instead of devel to avoid breaking regular builds of somd-freenrg on devel

### CODE REVIEW

**Comment by jmichel80** [comment]
@chryswoods  do you have suggestions for resolving the significant conflicts ?

**Comment by chryswoods** [comment]
Thanks - looks like a good PR on a quick scan.

All the conflicts look like they are in the wrappers. This happens a lot because sometimes the wrapper generation on different machines can give very different results. They aren't "real" conflicts as such - as these files are auto-generated from the source in corelib.

The way to solve this is to pull in from devel and to then use the wrapper docker container to regenerate the wrappers. I can do this if you want?

**Comment by jmichel80** [comment]
If possible I would prefer avoiding a pull from devel because of the code changes in wrapper/Tools/OpenMMMD.py 

we have created a new Sire OpenMM integrator to avoid breaking existing functionality but the logic to handle that selection is in the Python layer. The risks are low but there is a chance to accidentally mess up with code used by several groups.

**Comment by chryswoods** [comment]
That's ok. I can make the changes more surgically if you want? It would be pulling in all the C++ Python wrappers from devel to reset the conflicts. Then pulling in any changes to the C++ files in corelib except for the OpenMM ones. This should preserve the new code and the Python module. Then I can regenerate the wrappers in Move so that the new OpenMM classes are wrapped. This should then result in a pull request with no conflicts (if it all works ;-))

**Comment by jmichel80** [comment]
If you have the time to do it that would be really useful ! I am always a bit nervous about wrapper updates.

**Comment by chryswoods** [comment]
Ok - I am doing this now. I am in the process of compiling and testing locally before I push back to the `feature_pmefep` branch.

My process was to copy all of `devel` into `feature_pmefep` and then restore all of the files that had changed in `corelib`, `wrapper/Tools` and `wrapper/python/scripts`. I then fixed the `corelib/src/lib/openmm*.cpp` files by adding `#include "SireMol/core.h"` as this is a new header file that collects together all of the core includes needed for SireMol (stops a lot of wrapper compiler problems because of missing template definitions).

I then regenerated all of the wrappers in `wrappers/Move`, which brought in all of the new `OpenMM*` class wrappers.

This should mean that `feature_pmefep` is now almost identical to `devel`, except for the changes to the OpenMM-related files and the somd-related scripts and tools. I'll be able to check once I commit, as I will see what would then be changed by the pull request.

**Comment by chryswoods** [comment]
Ok - I think this is done. I've looked at the "Files Changed" tab and now there are only 20 files that have changed. These match with what I would expect (OpenMM files in corelib and their corresponding wrappers).

@jmichel80 - could you pull this version to your machine, compile it and then double-check that everything is ok?

**Comment by jmichel80** [comment]
Thanks !!! Yes the code compiles on my VM. I will run more tests over the coming weeks to make sure that the old functionality has been preserved

**Pull request merged**
